config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "events#index"
  get 'events/search'
  resources :events, only: [:new, :create, :show, :destroy, :edit, :update] do
    resources :comments, only: :create
    member do
      post "add", to: "favorites#create"
      get "show_favorites" => "favorites#show_favorites"
    end
    collection do
      get 'search_tag'
    end
  end
  resources :users, only: :show 
  resources :favorites, only: [:destroy, :index]
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :event

  validates :user_id, uniqueness: { scope: :event_id }
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def index
    @user = current_user
    @favorites = Favorite.where(user_id: @user.id).all
  end

  def create
    @user_id = current_user.id
    @event_id = Event.find(params[:id]).id
    @favorite = Favorite.new(event_id: @event_id, user_id: @user_id)
    if @favorite.save
      redirect_to event_path, notice: 'お気に入りに登録しました'
    else
      flash[:aleat] = '既に登録されています'
      redirect_to event_path
    end
  end

  def show_favorites
    @event = Event.find(params[:id])
    @favorites = Favorite.where(event_id: @event.id).all
  end

  def destroy
    @favorite = Favorite.find(params[:id])
    redirect_to favorites_path(current_user) if @favorite.destroy
  end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/views/favorites/index.html.erb
<div class="favorite__main">
  <h2>お気に入りのイベント</h2>
      <% @favorites.each do |favorite| %>
        <% event = Event.find(favorite.event_id) %>
          <div class="name3"><%= link_to event.name, event_path(event) %></div>
          <div class="name2"><%= link_to "参加中のイベントから削除",favorite_path(favorite), method: :delete %></div>
      <% end %>
</div>

app/views/favorites/show_favorite.html.erb
<h2>ユーザー一覧(<%= @favorites.length %>人)</h2>

    <% @favorites.each do |favorite| %>
      <% @user_id = favorite.user_id %>
      <% user = User.find(@user_id) %>
      <div class ="name2">
        <%= link_to user.usernickname ,user_path(user) %><br/>
      </div>
    <% end %>