config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "events#index"
  get 'events/search'
  resources :events, only: [:new, :create, :show, :destroy, :edit, :update] do
    resources :comments, only: :create
    member do
      post "add", to: "favorites#create"
      get "show_favorites" => "favorites#show_favorites"
    end
    collection do
      get 'search_tag'
    end
  end
  resources :users, only: :show 
  resources :favorites, only: [:destroy, :index]
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
end

app/models/event.rb
class Event < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :user
  has_many_attached :images
  belongs_to :facility
  belongs_to :scale
  belongs_to :category
  has_many :event_tag_relations, dependent: :destroy
  has_many :tags, through: :event_tag_relations, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites
  has_many :users, through: :favorites

  with_options presence: true do
    validates :name
    validates :explanation
    validates :facility_id
    validates :scale_id
    validates :category_id
  end
  with_options numericality: { other_than: 1 } do
    validates :facility_id
    validates :scale_id
    validates :category_id
  end

  def save_tags(saveevent_tags)
    current_tags = tags.pluck(:tag_name) unless tags.nil?
    old_tags = current_tags - saveevent_tags
    new_tags = saveevent_tags - current_tags

    old_tags.each do |old_name|
      tags.delete Tag.find_by(tag_name: old_name)
    end

    new_tags.each do |new_name|
      micropost_tag = Tag.find_or_create_by(tag_name: new_name)
      tags << micropost_tag
    end
  end

  def self.search(search)
    if search != ''
      Event.joins(:tags).where('name LIKE ? OR tag_name LIKE ?', "%#{search}%", "%#{search}%")
      # binding.pry
    else
      Event.all
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, only: [:edit, :destroy, :new, :create]
  before_action :search_event, only: [:index, :search]

  def index
    @events = Event.all
  end

  def new
    @event = Event.new
  end

  def create
    @event = current_user.events.build(event_params)
    tag_list = params[:event][:tag_ids].split(',')
    if @event.save
      @event.save_tags(tag_list)
      redirect_to root_url, notice: 'イベントを投稿しました'
    else
      render 'new'
    end
  end

  def search
    @results = @p.result
  end

  def search_tag
    @events = Event.search(params[:keyword])
  end

  def show
    @event = Event.find(params[:id])
    @comment = Comment.new
    @comments = @event.comments.includes(:user)
  end

  def edit
    @event = Event.find(params[:id])
    @tag_list = @event.tags.pluck(:tag_name).join(',')
  end

  def update
    @event = Event.find(params[:id])
    tag_list = params[:event][:tag_names].to_s.split(',')
    if @event.update_attributes(event_params)
      @event.save_tags(tag_list)
      redirect_to @event, notice: 'イベントを編集しました'
    else
      render 'edit'
    end
  end

  def destroy
    @event = Event.find(params[:id])
    redirect_to root_path, notice: 'イベントを削除しました' if @event.destroy
  end

  private

  def event_params
    params.require(:event).permit(:name, :explanation, :facility_id, :scale_id, :category_id, :volunteer,
                                  images: []).merge(user_id: current_user.id)
  end

  def tag_params
    params.require(:event).permit(:tag_names)
  end

  def search_event
    @p = Event.ransack(params[:q])
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_event.html.erb
<div class="card">
  <div link_to event_path(event.id), class="events">
    <div class="event">
      <%= link_to event.name, event_path(event.id), class: :card__title%>
      <% event.images.each do |image| %>
        <%= link_to image_tag(image, class: 'images'), event_path(event.id), class:  :home_image %>
        <% break %>
      <% end %>
    </div>
    <div class="card__body">
      <% event.tags.each do |tag| %>
        #<%= link_to tag.tag_name,event_path(event.id) %>
      <% end %>
      <%= link_to event.user.nickname, user_path(event.user), class: :card__user %>
    </div>
  </div>
</div>

app/views/events/_form.html.erb
<%# <%= form_with model: @event, url: events_path, local: true do |f| %>
  <%= render 'shared/error_messages', model: f.object %>
  <div class="field">
    <label class="label">イベント名</label>
    <%= f.text_field :name, class: :form_control %>
  </div>

  <div class="field">
    <label class="label">説明</label>
    <%= f.text_area :explanation, class: :form__text %>
  </div>

  <div class="field">
    <label class="label">ボランティア（任意)</label>
    <%= f.text_area :volunteer, class: :form__text %>
  </div>

  <div class="field", id='tag-field'>
    <label class="label">タグ</label>
    <%= f.text_field :tagname, class:"input-tag" %>
  </div>
  <div class="kouho", id="search-result" >
  </div>
    
  <div class="field">
    <label class="label">施設種類</label>
    <%= f.collection_select(:facility_id, Facility.all, :id, :name, {}, {class:"select-box"}) %>
  </div>
    
  <div class="field">
    <label class="label">規模</label>
    <%= f.collection_select(:scale_id, Scale.all, :id, :name, {}, {class:"select-box"}) %>
  </div>
    
  <div class="field">
    <label class="label">カテゴリー</label>
    <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"select-box"}) %>
  </div>

  <div class="field">
    <label class="label">画像</label>
    <%= f.file_field :images, name: 'event[images][]', id: 'event_image', class:"select-box-image" %>
    <div id="image-list"></div>
  </div>

  <div class="actions">
    <%= f.submit "保存する", class: :form__btn  %>
  </div>
<% end %> 

app/views/events/edit.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <span class="page-heading">
        編集
      </span>
          <%= form_with model: @event, url: event_path, local: true do |f| %>
            <%= render 'shared/error_messages', model: f.object %>
            <div class="field">
            <label class="label">イベント名</label>
            <%= f.text_field :name, class: :form_control %>
          </div>

          <div class="field">
            <label class="label">説明</label>
            <%= f.text_area :explanation, class: :form__text %>
          </div>

          <div class="field">
            <label class="label">ボランティア（任意)</label>
            <%= f.text_area :volunteer, class: :form__text %>
          </div>

          <div class="field", id='tag-field'>
            <label class="label">タグ（任意)</label>
            <%= f.text_field :tag_names,value: @tag_list,\
              placeholder: "タグをつける。複数つけるには','で区切ってください" %>
    
          <div class="field">
            <label class="label">施設種類</label>
            <%= f.collection_select(:facility_id, Facility.all, :id, :name, {}, {class:"select-box"}) %>
          </div>
    
          <div class="field">
            <label class="label">規模</label>
            <%= f.collection_select(:scale_id, Scale.all, :id, :name, {}, {class:"select-box"}) %>
          </div>
    
          <div class="field">
            <label class="label">カテゴリー</label>
            <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"select-box"}) %>
          </div>

          <div class="field">
            <label class="label">画像</label>
            <%= f.file_field :images, name: 'event[images][]', id: 'event_image', class:"select-box-image" %>
          <div id="image-list"></div>
          </div>

          <div class="actions">
            <%= f.submit "保存する", class: :form__btn  %>
    
          </div>
         <% end %>
        <%# 部分テンプレートでフォームを表示する %>
    </div>
  </div>
</div>

app/views/events/index.html.erb
<main class="main">
  <div class="gest">
    <%= link_to 'ゲストログイン（閲覧用）', users_guest_sign_in_path, method: :post %>
  </div>
  <div class="inner">
   絞り込み検索
  <%= search_form_for @p, url: events_search_path do |f| %>
    <%= f.collection_select(:facility_id_eq, Facility.all, :id, :name, {}, {class:"select-box"}) %> 
    <%= f.collection_select(:scale_id_eq, Scale.all, :id, :name, {}, {class:"select-box"}) %> 
    <%= f.collection_select(:category_id_eq, Category.all, :id, :name, {}, {class:"select-box"}) %>
    <%= f.submit "検索", class: "search-btn" %>
  <% end %>
  <%= form_with(url: search_tag_events_path, local: true, method: :get, class: "search-form") do |form| %>
    <%= form.text_field :keyword, placeholder: "タイトル・タグ検索", class: "search-input" %>
    <%= form.submit "検索", class: "search-btn" %>
  <% end %>
  
    <% if user_signed_in? %>
       <div class="greeting"> 
        <%= "こんにちは、" %>
          <%= link_to "#{current_user.nickname}さん", user_path(current_user.id), class: :greeting__link%> 
       </div> 
    <% end %>
    <div class="card__wrapper">
      <%= render partial: 'event', collection: @events %>
      
</main>

app/views/events/new.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <span class="page-heading">
        新規投稿
      </span>
          <%= form_with model: @event, url: events_path, local: true do |f| %>
            <%= render 'shared/error_messages', model: f.object %>
            <div class="field">
            <label class="label">イベント名</label>
            <%= f.text_field :name, class: :form_control %>
          </div>

          <div class="field">
            <label class="label">説明</label>
            <%= f.text_area :explanation, class: :form__text %>
          </div>

          <div class="field">
            <label class="label">ボランティア（任意)</label>
            <%= f.text_area :volunteer, class: :form__text %>
          </div>
          <label class="label">タグ（任意)</label>
          <%= f.text_field :tag_ids, class: "form-control", id:'tag_ids',\
            placeholder: "複数つけるには','で区切ってください" %>
    
          <div class="field">
            <label class="label">施設種類</label>
            <%= f.collection_select(:facility_id, Facility.all, :id, :name, {}, {class:"select-box"}) %>
          </div>
    
          <div class="field">
            <label class="label">規模</label>
            <%= f.collection_select(:scale_id, Scale.all, :id, :name, {}, {class:"select-box"}) %>
          </div>
    
          <div class="field">
            <label class="label">カテゴリー</label>
            <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"select-box"}) %>
          </div>

          <div class="field">
            <label class="label">画像(任意)</label>
              <%= f.file_field :images, name: 'event[images][]', id: 'event_image', class:"select-box-image" %> 
              <div id="image-list"></div>
          </div>
          

          <div class="actions">
            <%= f.submit "保存する", class: :form__btn  %>
          </div>
         <% end %>
    </div>
  </div>
</div>

app/views/events/search.html.erb
<%= form_with(url: search_tag_events_path, local: true, method: :get, class: "search-form") do |form| %>
    <%= form.text_field :keyword, placeholder: "タイトル・タグ検索", class: "search-input" %>
    <%= form.submit "検索", class: "search-btn" %>
  <% end %>
  <%= search_form_for @p, url: events_search_path do |f| %>
    <%= f.collection_select(:facility_id_eq, Facility.all, :id, :name, {}, {class:"select-box"}) %> 
    <%= f.collection_select(:scale_id_eq, Scale.all, :id, :name, {}, {class:"select-box"}) %> 
    <%= f.collection_select(:category_id_eq, Category.all, :id, :name, {}, {class:"select-box"}) %>
    <%= f.submit "検索", class: "search-btn" %>
  <% end %>
<div class="card__wrapper">
  <% if @results.length !=0 %>
    <% @results.each do |result| %>
      <li>
        <%= link_to result.name, event_path(result.id) %>
        <% result.images.each do |image| %>
          <%= link_to image_tag(image, class: 'images'), event_path(result.id), class:  :home_image %>
          <% break %>
        <% end %>
      </li>
    <% end %>
  <% else %>
    該当するイベントはありません
  <% end %>

app/views/events/search_tag.html.erb
<%= form_with(url: search_tag_events_path, local: true, method: :get, class: "search-form") do |form| %>
  <%= form.text_field :keyword, placeholder: "投稿を検索する", class: "search-input" %>
  <%= form.submit "検索", class: "search-btn" %>
<% end %>
<div class="card__wrapper">
  <% @events.each do |event| %>
    <%= render partial: "event", locals: { event: event } %>
  <% end %>

app/views/events/show.html.erb
<main class="main">
  <div class="inner">
    <div class="prototype__wrapper">
      <div class="favorite">
          <%= link_to "お気に入り", add_event_path(@event), method: :post %>
      </div>
      <div class="prototype__hedding">
          <%= @event.name %>
      </div>
      <div class="event_hedding">
        <div class="event__hedding__name">
          <%= @event.facility.name %>
        </div>
        <div class="event__hedding__name">
          <%= @event.scale.name %>
        </div>
        <div class="event__hedding__name">
          <%= @event.category.name %>
        </div>
        <div class="event__hedding__name">
          <%= @event.volunteer %>
        </div>
        <div class="event__hedding__right">
          <%= @event.facility.name %>
        </div>
      </div>
      <div class="event_hedding">
        <div class="event__hedding__tag">
          <% @event.tags.each do |tag| %>
            #<%= tag.tag_name %>
          <% end %>
        </div>
      </div>
      <%= link_to @event.user.nickname, user_path(@event.user), class: :prototype__user %>
      <% if user_signed_in? && current_user.id == @event.user_id %>
      <%# プロトタイプの投稿者とログインしているユーザーが同じであれば以下を表示する %>
        <div class="prototype__manage">
          <%= link_to "編集する", edit_event_path(@event.id), class: :prototype__btn %>
          <%= link_to "削除する", event_path(@event.id), method:  :delete, class: :prototype__btn %>
        </div>
      <% end %>
      <div class="prototype__image">
        <% @event.images.each do |image| %>
          <%= image_tag image, class:  :home_image %>
        <% end %>
      </div>
      <div class="prototype__body">
        <div style="white-space:pre-wrap", class="prototype__detail">
          <p class="detail__title">説明</p>
          <div class="detail__message">
            <%= @event.explanation %>
          </div>
        </div>
      </div>
      <div class="prototype__comments">
        <% if user_signed_in? %>
           <%= form_with model: [@event, @comment], local: true do |f|%>
            <div class="field">
               <%= f.label "コメント" %><br />
               <%= f.text_field :text %>
            </div>
            <div class="actions">
               <%= f.submit "送信する", class: :form__btn  %>
            </div>
           <% end %> 
        <% end %> 
        <ul class="comments_lists">
        <%=  @comments %>
          <% @comments.each do |comment| %>
            <li class="comments_list">
              <%= comment.text %>
              <%= link_to comment.user.nickname, user_path(comment.user), class: :comment_user %>
            </li>
          <% end%>
          
        </ul>
      </div>
    </div>
  </div>
</main>