config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "events#index"
  get 'events/search'
  resources :events, only: [:new, :create, :show, :destroy, :edit, :update] do
    resources :comments, only: :create
    member do
      post "add", to: "favorites#create"
      get "show_favorites" => "favorites#show_favorites"
    end
    collection do
      get 'search_tag'
    end
  end
  resources :users, only: :show 
  resources :favorites, only: [:destroy, :index]
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ActiveHash::Base
  self.data = [
    { id: 1, name: 'カテゴリー' },
    { id: 2, name: '初詣・新年会' },
    { id: 3, name: '節分' },
    { id: 4, name: 'ひな祭り' },
    { id: 5, name: 'お花見' },
    { id: 6, name: '端午の節句' },
    { id: 7, name: '母の日' },
    { id: 8, name: '父の日' },
    { id: 9, name: '七夕' },
    { id: 10, name: '夏祭り' },
    { id: 11, name: '十五夜' },
    { id: 12, name: '敬老の日' },
    { id: 13, name: '運動会' },
    { id: 14, name: '紅葉狩り' },
    { id: 15, name: 'クリスマス会' },
    { id: 16, name: '年越し' },
    { id: 17, name: '誕生日会' },
    { id: 18, name: '音楽会' },
    { id: 19, name: '食事関連' },
    { id: 20, name: '外出' },
    { id: 21, name: 'その他' }
  ]
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :event
  validates :text, presence: true
end

app/models/event.rb
class Event < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :user
  has_many_attached :images
  belongs_to :facility
  belongs_to :scale
  belongs_to :category
  has_many :event_tag_relations, dependent: :destroy
  has_many :tags, through: :event_tag_relations, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites
  has_many :users, through: :favorites

  with_options presence: true do
    validates :name
    validates :explanation
    validates :facility_id
    validates :scale_id
    validates :category_id
  end
  with_options numericality: { other_than: 1 } do
    validates :facility_id
    validates :scale_id
    validates :category_id
  end

  def save_tags(saveevent_tags)
    current_tags = tags.pluck(:tag_name) unless tags.nil?
    old_tags = current_tags - saveevent_tags
    new_tags = saveevent_tags - current_tags

    old_tags.each do |old_name|
      tags.delete Tag.find_by(tag_name: old_name)
    end

    new_tags.each do |new_name|
      micropost_tag = Tag.find_or_create_by(tag_name: new_name)
      tags << micropost_tag
    end
  end

  def self.search(search)
    if search != ''
      Event.joins(:tags).where('name LIKE ? OR tag_name LIKE ?', "%#{search}%", "%#{search}%")
      # binding.pry
    else
      Event.all
    end
  end
end

app/models/event_tag_relation.rb
class EventTagRelation < ApplicationRecord
  belongs_to :event
  belongs_to :tag
end

app/models/facility.rb
class Facility < ActiveHash::Base
  self.data = [
    { id: 1, name: '施設種類' },
    { id: 2, name: 'デイケア・デイサービス' },
    { id: 3, name: 'ケアハウス・高齢者住宅' },
    { id: 4, name: '従来型入所' },
    { id: 5, name: 'ユニット型入所' },
    { id: 6, name: 'その他' }
  ]
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :event

  validates :user_id, uniqueness: { scope: :event_id }
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: 'User'
  belongs_to :following, class_name: 'User'
  validates :follower_id, presence: true
  validates :following_id, presence: true
end

app/models/scale.rb
class Scale < ActiveHash::Base
  self.data = [
    { id: 1, name: '規模' },
    { id: 2, name: '大行事(施設全体)' },
    { id: 3, name: '小行事（フロア)' },
    { id: 4, name: 'その他' }
  ]
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :event_tag_relations, dependent: :destroy
  has_many :events, through: :event_tag_relations, dependent: :destroy
  validates :tag_name, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :comments, dependent: :destroy
  has_many :events
  validates :nickname, presence: true
  validates :profile, presence: true
  validates :occupation, presence: true
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :favorites, dependent: :destroy
  has_many :events, through: :favorites
  has_many :following_relationships, foreign_key: 'follower_id', class_name: 'Relationship', dependent: :destroy
  has_many :followings, through: :following_relationships
  has_many :follower_relationships, foreign_key: 'following_id', class_name: 'Relationship', dependent: :destroy
  has_many :followers, through: :follower_relationships

  def addsub(event)
    favorites.find_or_create_by(event_id: event.id)
  end

  def removesub(_evenr)
    favorite = favorites.find_by(event_id: event.id)
    favorite.destroy if favorite
  end

  def checksub?(event)
    events.include?(event)
  end

  def self.guest
    find_or_create_by!(nickname: 'ゲスト', email: 'guest@example.com', profile: 'レクが得意', occupation:'介護士') do |user|
      user.password = SecureRandom.urlsafe_base64
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @event = Event.find(params[:event_id])
    @comment = @event.comments.new(comment_params)
    if @comment.save
      redirect_to event_path(@comment.event)
    else
      render 'events/show'
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, event_id: params[:event_id])
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, only: [:edit, :destroy, :new, :create]
  before_action :search_event, only: [:index, :search]

  def index
    @events = Event.all
  end

  def new
    @event = Event.new
  end

  def create
    @event = current_user.events.build(event_params)
    tag_list = params[:event][:tag_ids].split(',')
    if @event.save
      @event.save_tags(tag_list)
      redirect_to root_url, notice: 'イベントを投稿しました'
    else
      render 'new'
    end
  end

  def search
    @results = @p.result
  end

  def search_tag
    @events = Event.search(params[:keyword])
  end

  def show
    @event = Event.find(params[:id])
    @comment = Comment.new
    @comments = @event.comments.includes(:user)
  end

  def edit
    @event = Event.find(params[:id])
    @tag_list = @event.tags.pluck(:tag_name).join(',')
  end

  def update
    @event = Event.find(params[:id])
    tag_list = params[:event][:tag_names].to_s.split(',')
    if @event.update_attributes(event_params)
      @event.save_tags(tag_list)
      redirect_to @event, notice: 'イベントを編集しました'
    else
      render 'edit'
    end
  end

  def destroy
    @event = Event.find(params[:id])
    redirect_to root_path, notice: 'イベントを削除しました' if @event.destroy
  end

  private

  def event_params
    params.require(:event).permit(:name, :explanation, :facility_id, :scale_id, :category_id, :volunteer,
                                  images: []).merge(user_id: current_user.id)
  end

  def tag_params
    params.require(:event).permit(:tag_names)
  end

  def search_event
    @p = Event.ransack(params[:q])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @events = @user.events
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_flash.html.erb
<div class="notifications">
 <div class="notice">メッセージが送信されました</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <script src="index.js"></script>
    <div class="messege">
        <% flash.each do |key, value| %>
          <%= content_tag(:div, value, class: key) %>
        <% end %>
    </div>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Asomemo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+JP:400,700,900&display=swap" rel="stylesheet">
  </head>

  <body>
    <script src="http://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.5.1.min.js">
    <script src="./js/script.js"></script>
    <header class="header">
      <div class="inner">
        <div class="nav">
          
          <% if user_signed_in? %>
            <div class="nav__left"> 
              <%= link_to image_tag("logo9.png", class: :logo_sub), favorites_path(current_user) %>
              <%= link_to image_tag("logo8.png", class: :logo_sub), user_path(current_user.id), class: :greeting__link%> 
            </div> 
          <% else %>
            <div class="nav__left"> 
              <%= link_to image_tag("logo9.png", class: :logo_sub), root_path %>
              <%= link_to image_tag("logo8.png", class: :logo_sub), root_path %>
            </div> 
          <% end %>
          <div class="nav__main">
            <%= link_to image_tag("logo.png", class: :logo_main), root_path %>
          </div>
          <% if user_signed_in? %>
             <div class="nav__right"> 
               <%= link_to image_tag("logo6.png", class: :logo_sub), destroy_user_session_path, method:  :delete %>
               <%= link_to image_tag("logo7.png", class: :logo_sub), new_event_path %>
             </div> 
          <% else %>
            <div class="nav__right">
              <%= link_to image_tag("logo3.png", class: :logo_sub), new_user_session_path %>
              <%= link_to image_tag("logo5.png", class: :logo_sub), new_user_registration_path %>
            </div>
          <% end %>
        </div>
      </div>
    </header>
    <%= yield %>
    <footer class="footer">
      <p class="copyright">Copyright © PROTO SPACE All rights reserved.</p>
    </footer>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>